export class EmpLeave {
    g_APPROVALREQ_ID:number;
    // lEmpleaveId:number;
    gCompanyId:number;
    gHoldingId:number;
    isActive:string;
    createdBy :number;
    updatedBy:number;
    created :string;
    updated :string;
    description:string;
    documentno :string;
    xEmployeeId:number;
    startdate :string;
    enddate :string;
    stdate : string;
    endate : string;
    trxdate : string;
    leavedays :number;
    upLeavedays:number;
    isHalfday:string;
    encashment:string;
    xLeaveitemId:number;
    processed :string;
    remarks :string;
    actualend :string;
    datetrx: string;
    leavePurpose: string;
    contactDetails: string;
    fromAirsectorId:number;
    toAirsectorId:number;
    airtktEntitled:number;
    airtktClass:number;
    airtktCb:string;
    file:any;
    std:string;
    end:string;
    trxd:string;
    ticketAmount:any;
    paidLeaveDays:any;
    unpaidLeaveDays:any; 
    islwp:any;
    lastleavesettledupto :string;
    curleavesettledupto :string;
    lastticketsettledupto : string;
    curticketsettledupto : string;
    toResumedt : string;
    lastlvstdt :string;
    curlvstdt :string;
    lastticketstdt : string;
    curticketstdt : string;
    resumedt: string;
    encashDays:number;
}